const esbuild = require('esbuild');
const path = require('path');

esbuild.build({
  entryPoints: [path.resolve(__dirname, '../js/**/*.jsx')],
  bundle: false,
  outdir: path.resolve(__dirname, '../js'),
  banner: {
    js: '/**\n * Generated by a build script. Do not modify.\n * Check orginal .jsx file.\n */',
  },
});
