<?php

use Drupal\views\ViewExecutable;
use Drupal\views\Plugin\views\query\QueryPluginBase;

/**
 * Gutenberg Editor Page.
 */
function govcon_custom_preprocess_html(&$variables) {
  $route_match = \Drupal::routeMatch();
  $route_name = $route_match->getRouteName();
  // Check For Edit Form Page
  if ($route_name === 'entity.node.edit_form') {
    $node = $route_match->getParameter('node');
    // Check for Landing Page Content Type
    if ($node instanceof \Drupal\node\NodeInterface && $node->bundle() === 'landing_page') {
      // Check for Background Image Field
      if ($node->hasField('field_background_image') && !$node->get('field_background_image')->isEmpty()) {
        $media_entities = $node->get('field_background_image')->referencedEntities();
        // Check for Media Entity
        if (!empty($media_entities) && $media_entities[0] instanceof \Drupal\media\Entity\Media) {
          $media = $media_entities[0];
          // Check for Image Field
          if ($media->hasField('field_media_image') && !$media->get('field_media_image')->isEmpty()) {
            $file = $media->get('field_media_image')->entity;
            if ($file instanceof \Drupal\file\Entity\File) {
              $image_url = \Drupal::service('file_url_generator')->generateAbsoluteString($file->getFileUri());
              // Add CSS variable to style the background image
              $variables['attributes']['style'][] = "--background-image: url('{$image_url}')";
            }
          }
        }
      }
    }
  }
}

/**
 * Implements hook_views_query_alter().
 */
function govcon_custom_views_query_alter(ViewExecutable $view, QueryPluginBase $query) {
  if (
    ($view->id() === 'announcements' && $view->current_display === 'all_announcement') ||
    ($view->id() === 'announcements' && $view->current_display === 'recent_announcement') ||
    ($view->id() === 'sponsors' && $view->current_display === 'sponsors')
  ) {

    // Get the taxonomy term ID dynamically (can be from the URL, user input, etc.).
    $config = \Drupal::config('govcon_custom.settings');
    $conference_year_id = $config->get('conference_year') ?? '';

    if (!empty($conference_year_id) && is_numeric($conference_year_id)) {

      foreach ($query->where as &$where_group) {
        foreach ($where_group['conditions'] as &$condition) {
          if (strpos($condition['field'], 'node__field_conference_year.field_conference_year_target_id = :node__field_conference_year_field_conference_year_target_id') !== FALSE) {
            $condition['value'] = [
              ':node__field_conference_year_field_conference_year_target_id' => $conference_year_id];
          }
        }
      }
    }
  }
}
