#!/bin/bash

## Description: Initialize application.
## Usage: init
## Example: ddev init

# This can't work unless you have a solr service,
# See https://ddev.readthedocs.io/en/stable/users/extend/additional-services/

echo "Authorize ssh keys in docker containers."
ddev auth ssh

echo "Running composer."
ddev composer install

echo "Pulling latest database from dev."
ddev pull pantheon -y

echo "Running drush deploy"
ddev drush deploy -y
ddev drush ia --yes --choice=full

echo "Executing frontend setup and build"
ddev frontend

echo "Your site is ready to use. Below is the information."
ddev describe
