/**
 * Generated by a build script. Do not modify.
 * Check orginal .jsx file.
 */
((Drupal2, wp2) => {
  const { t } = Drupal2;
  const { hooks, blockEditor } = wp2;
  const { addFilter } = hooks;
  const { BlockControls } = blockEditor;
  function withFieldMappingWarning(Edit) {
    return (props) => {
      const { isSelected, attributes } = props;
      const { className } = attributes;
      const isFeaturedImage = className ? className.includes("is-article-featured-image") : false;
      return /* @__PURE__ */ React.createElement(React.Fragment, null, isSelected && isFeaturedImage && /* @__PURE__ */ React.createElement("div", { className: "block-warning-label" }, "\u26A0\uFE0F ", t("Some attributes won't be applied on frontend.")), /* @__PURE__ */ React.createElement(Edit, { ...props }));
    };
  }
  addFilter(
    "blocks.registerBlockType",
    "gutenberg-starter/extended-image",
    (settings, name) => {
      if (name !== "core/image") {
        return settings;
      }
      return {
        ...settings,
        styles: [],
        edit: withFieldMappingWarning(settings.edit)
      };
    }
  );
})(Drupal, wp);
